/**
 * Shared type definitions for the KisanMind orchestration layer
 */

/**
 * Farmer profile extracted by the intake agent from raw input
 */
export interface FarmerProfile {
  location: {
    latitude: number;
    longitude: number;
    state: string;
    district: string;
    village?: string;
  };
  landSize: {
    acres: number;
    irrigated_acres?: number;
  };
  waterSource: string;
  currentCrops: string[];
  previousCrops: string[];
  budget_INR?: number;
  farmingExperience?: string;
  soilType?: string;
  language: string;
  rawInput: string;
  confidence: number;
  landUseValidation?: {
    isAgricultural: boolean;
    landCoverType: string;
    confidence: 'high' | 'medium' | 'low';
    warning?: string;
    source: string;
  };
}

/**
 * MCP server response wrapper
 */
export interface MCPServerResponse {
  server: string;
  status: 'success' | 'partial' | 'error' | 'timeout';
  data: unknown;
  responseTime_ms: number;
  error?: string;
}

/**
 * Aggregated data from all 5 MCP servers
 */
export interface AggregatedIntelligence {
  farmerProfile: FarmerProfile;
  soilIntel: MCPServerResponse;
  waterIntel: MCPServerResponse;
  climateIntel: MCPServerResponse;
  marketIntel: MCPServerResponse;
  schemeIntel: MCPServerResponse;
  orchestrationMeta: {
    totalTime_ms: number;
    successfulServers: number;
    failedServers: string[];
    timestamp: string;
  };
}

/**
 * Final farming decision report generated by the synthesis agent
 */
export interface FarmingDecisionReport {
  summary: string;
  primaryRecommendation: {
    crop: string;
    variety: string;
    expectedProfit_per_acre: number;
    costEstimate_per_acre: number;
    sowingDate: string;
    spacing: string;
    seedRate: string;
    soilPreparation: string;
    confidence: string;
  };
  alternativeOptions: Array<{
    crop: string;
    expectedProfit_per_acre: number;
    reason: string;
  }>;
  waterStrategy: {
    irrigationMethod: string;
    waterSchedule: string;
    totalWaterRequirement: string;
    waterSavingTips: string[];
  };
  marketStrategy: {
    bestSellingTime: string;
    bestMarket: string;
    expectedPrice: number;
    storageAdvice: string;
    nearbyMandis: Array<{
      name: string;
      distance: number;
      currentPrice: number;
      coordinates: { lat: number; lon: number };
    }>;
  };
  governmentSupport: {
    schemesToApply: Array<{
      name: string;
      benefit: string;
      howToApply: string;
      deadline: string;
      eligibility: string;
    }>;
    totalBenefit: string;
  };
  riskAssessment: Array<{
    risk: string;
    severity: string;
    mitigation: string;
  }>;
  monthlyActionPlan: Array<{
    month: string;
    actions: string[];
  }>;
  disclaimer: string;
  language: string;
  generatedAt: string;
}

/**
 * Orchestrator configuration
 */
export interface OrchestratorConfig {
  anthropicApiKey: string;
  mcpServerTimeout_ms: number;
  intakeModel: string;
  synthesisModel: string;
  extendedThinkingBudget: number;
  maxRetries: number;
}
